version: "3"

services:
  jupyter:
    image: jupyter/datascience-notebook:python-3.9.10
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work

  rabbit:
    image: rabbitmq:management
    ports:
      - "15671:15671"
      - "15672:15672"
    volumes:
      - rabbit:/var/lib/rabbitmq

volumes:
  rabbit:
