version: "3"

services:
  jupyter:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work

  work-queue-python-worker:
    build:
      context: ./work-queue-python
    depends_on:
      - "rabbit"
      - "jupyter"
    restart: always

  work-queue-js-worker:
    build:
      context: ./work-queue-js
    depends_on:
      - "rabbit"
      - "jupyter"
    restart: on-failure

  pub-sub-js-subscriber:
    build: 
      context: ./pub-sub
    depends_on:
      - "rabbit"
      - "jupyter"
    restart: on-failure

  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit:/var/lib/rabbitmq

volumes:
  rabbit:
